// Shared data across all variants
const data = {
  // ===== CONFIG — swap these to wire up the contact form =====
  // Web3Forms: free service, no signup for basic use. Get a key at https://web3forms.com
  // Leave empty to fall back to mailto: (opens user's email client with prefilled body)
  web3formsKey: "",
  // ==========================================================

  name: "Giovanni Perniola",
  handle: "@giovascript99",
  email: "gioperniola1999@gmail.com",
  github: "giovascript99",
  roles: {
    it: ["Full Stack Developer", "Vibe & AI Coding Developer"],
    en: ["Full Stack Developer", "Vibe & AI Coding Developer"],
  },
  bio: {
    it: "Sviluppatore full stack con focus su vibe coding e AI-assisted development. Costruisco siti web su misura per aziende, combinando codice pulito, design intenzionale e strumenti AI di ultima generazione per consegnare prodotti veloci, eleganti e scalabili.",
    en: "Full stack developer focused on vibe coding and AI-assisted development. I build tailor-made websites for companies, combining clean code, intentional design and cutting-edge AI tools to ship fast, elegant and scalable products.",
  },
  shortBio: {
    it: "Full stack dev che parla con le AI e costruisce siti che convertono.",
    en: "Full stack dev who speaks AI and builds websites that convert.",
  },
  projects: [
    {
      id: "oralia",
      name: "Oralia",
      category: { it: "Studio Dentistico", en: "Dental Practice" },
      year: "2025",
      tagline: {
        it: "L'eccellenza clinica incontra l'arte del sorriso",
        en: "Clinical excellence meets the art of the smile",
      },
      description: {
        it: "Sito vetrina per studio dentistico storico. Hero cinematografica, prenotazione diretta via WhatsApp, form contatti multi-step, sezione blog e certificazioni ANDI. Focus su conversione e trust.",
        en: "Showcase website for a historic dental practice. Cinematic hero, direct WhatsApp booking, multi-step contact form, blog section and ANDI certifications. Focused on conversion and trust.",
      },
      stack: ["Next.js", "React", "Tailwind", "Framer Motion", "Sanity CMS"],
      features: {
        it: ["Prenotazione WhatsApp", "Form multi-step", "CMS headless", "SEO locale"],
        en: ["WhatsApp booking", "Multi-step form", "Headless CMS", "Local SEO"],
      },
      image: "/assets/oralia.jpg",
      color: "#3ea89a",
      liveUrl: "https://sito-dentista-demo.netlify.app/",
      caseStudy: {
        role: { it: "Design, sviluppo, deployment", en: "Design, development, deployment" },
        team: { it: "Solo (AI-assisted)", en: "Solo (AI-assisted)" },
        challenge: {
          it: "Uno studio dentistico cercava una presenza online all'altezza della qualità del servizio clinico. L'obiettivo: un sito moderno che ispirasse fiducia e rendesse la prenotazione un gesto naturale, senza frizione.",
          en: "A dental practice needed an online presence that matched the quality of its clinical service. The goal: a modern site that would build trust and make booking a natural, frictionless action.",
        },
        approach: {
          it: "Ho progettato un sito showcase con hero cinematografica, sistema di prenotazione WhatsApp in un click, form contatti multi-step e sezione blog alimentata da CMS headless. Certificazioni e testimonianze in evidenza, attenzione a SEO locale e performance.",
          en: "I designed a showcase site with a cinematic hero, one-click WhatsApp booking, a multi-step contact form and a blog section powered by a headless CMS. Certifications and testimonials in the spotlight, with a focus on local SEO and performance.",
        },
        outcome: {
          it: "Il risultato è un sito veloce, moderno e facilmente aggiornabile dallo staff — pronto per scalare con nuovi servizi e contenuti editoriali senza toccare il codice.",
          en: "The result is a fast, modern site that's easy for the staff to update — ready to scale with new services and editorial content without touching code.",
        },
      },
    },
    {
      id: "taverna",
      name: "Taverna del Porto",
      category: { it: "Ristorante", en: "Restaurant" },
      year: "2025",
      tagline: {
        it: "Sapori di mare dal cuore della Calabria",
        en: "Flavors of the sea from the heart of Calabria",
      },
      description: {
        it: "Sito bilingue per ristorante di pesce con vista mare. Menu dinamico, gallery immersiva, sezione 'La Cantina' per i vini, prenotazione tavolo integrata. Estetica editoriale e cinematografica.",
        en: "Bilingual site for a seafood restaurant with sea view. Dynamic menu, immersive gallery, 'La Cantina' wine section, integrated table reservation. Editorial and cinematic aesthetic.",
      },
      stack: ["Astro", "TypeScript", "GSAP", "Cloudinary", "i18n"],
      features: {
        it: ["Multilingua IT/EN", "Menu CMS", "Gallery immersiva", "Prenotazione online"],
        en: ["IT/EN multilingual", "Menu CMS", "Immersive gallery", "Online booking"],
      },
      image: "/assets/taverna.jpg",
      color: "#e88a3c",
      liveUrl: "https://demo-ristorante-jade.vercel.app/",
      caseStudy: {
        role: { it: "Design, sviluppo, i18n", en: "Design, development, i18n" },
        team: { it: "Solo (AI-assisted)", en: "Solo (AI-assisted)" },
        challenge: {
          it: "Un ristorante di pesce con forte stagionalità e clientela mista (locali e turisti) aveva bisogno di un sito capace di parlare a entrambi, mostrare i piatti con la cura che meritano e rendere la prenotazione semplice.",
          en: "A seafood restaurant with strong seasonality and a mixed clientele (locals and tourists) needed a site that could speak to both, showcase the dishes with the care they deserve, and make booking simple.",
        },
        approach: {
          it: "Ho costruito un sito bilingue IT/EN con estetica editoriale: tipografia serif per i piatti, gallery immersiva, menu strutturato e prenotazione online integrata. Focus su atmosfera, leggibilità e velocità di caricamento.",
          en: "I built a bilingual IT/EN site with an editorial aesthetic: serif typography for dishes, immersive gallery, structured menu, and integrated online booking. Focus on atmosphere, readability, and loading speed.",
        },
        outcome: {
          it: "Un sito che riflette l'identità del ristorante, accessibile in due lingue e pronto a crescere con il menu stagionale — senza dipendere da terze parti per gli aggiornamenti.",
          en: "A site that reflects the restaurant's identity, accessible in two languages and ready to grow with the seasonal menu — without relying on third parties for updates.",
        },
      },
    },
  ],
  stack: {
    frontend: ["React", "Next.js", "Astro", "TypeScript", "Tailwind", "Framer Motion", "GSAP"],
    backend: ["Node.js", "Express", "Supabase", "PostgreSQL", "Prisma", "REST", "tRPC"],
    ai: ["Claude", "GPT-4", "Cursor", "v0", "Windsurf", "Copilot", "LangChain"],
    tools: ["Git", "Vercel", "Docker", "Figma", "Sanity", "Cloudinary"],
  },
  skills: [
    { name: { it: "Vibe Coding", en: "Vibe Coding" }, level: 95, desc: { it: "Prompt precisi, iterazioni veloci, codice pulito", en: "Precise prompts, fast iterations, clean code" } },
    { name: { it: "AI-Assisted Dev", en: "AI-Assisted Dev" }, level: 92, desc: { it: "Claude, Cursor, Windsurf come parte del flusso", en: "Claude, Cursor, Windsurf as part of the flow" } },
    { name: { it: "Full Stack", en: "Full Stack" }, level: 88, desc: { it: "Dal DB al pixel, end-to-end ownership", en: "From DB to pixel, end-to-end ownership" } },
    { name: { it: "UI/UX Sensibility", en: "UI/UX Sensibility" }, level: 85, desc: { it: "Design intenzionale, dettagli curati", en: "Intentional design, crafted details" } },
    { name: { it: "Prompt Engineering", en: "Prompt Engineering" }, level: 90, desc: { it: "Contesto, constraints, esempi mirati", en: "Context, constraints, targeted examples" } },
  ],
  copy: {
    it: {
      heroKicker: "PORTFOLIO / 2026",
      availableStatus: "Disponibile per nuovi progetti",
      workCta: "I miei progetti",
      aboutKicker: "CHI SONO",
      aboutTitle: "Costruisco siti web per aziende,\ncon le AI come co-pilota.",
      stackKicker: "STACK",
      stackTitle: "Strumenti del mestiere",
      skillsKicker: "SKILLS",
      skillsTitle: "Come lavoro",
      projectsKicker: "LAVORI",
      projectsTitle: "Progetti recenti",
      contactKicker: "CONTATTI",
      contactTitle: "Parliamo del tuo progetto",
      contactLead: "Hai un'idea, un sito da rifare, un'azienda che vuole farsi trovare online? Scrivimi.",
      viewLive: "Vedi live",
      caseStudy: "Case study",
      scrollHint: "Scroll",
      footerNote: "Progettato & codato con AI come co-pilota",
      labelYear: "Anno",
      labelStack: "Stack",
      labelFeatures: "Features",
      navWork: "Lavori",
      navAbout: "About",
      navStack: "Stack",
      navContact: "Contatti",
      // Case study
      caseBackTo: "Torna al portfolio",
      caseRole: "Ruolo",
      caseTeam: "Team",
      caseYear: "Anno",
      caseChallenge: "La sfida",
      caseApproach: "L'approccio",
      caseOutcome: "Risultato",
      caseStackTitle: "Stack tecnologico",
      caseFeaturesTitle: "Features chiave",
      caseCtaText: "Vuoi un sito così per la tua attività?",
      caseCtaBtn: "Iniziamo",
      caseComingSoon: "Live a breve",
      // Contact form
      formName: "Nome",
      formEmail: "Email",
      formCompany: "Azienda (opzionale)",
      formBudget: "Budget indicativo",
      formMessage: "Raccontami il progetto",
      formSend: "Invia messaggio",
      formSending: "Invio in corso…",
      formSuccess: "Messaggio inviato. Ti rispondo entro 24h.",
      formError: "Qualcosa è andato storto. Riprova o scrivimi direttamente via email.",
      formRequired: "Campo obbligatorio",
      formInvalidEmail: "Email non valida",
      formBudgetOpts: ["< 2k €", "2–5k €", "5–10k €", "10k+ €", "Da definire"],
    },
    en: {
      heroKicker: "PORTFOLIO / 2026",
      availableStatus: "Available for new projects",
      workCta: "My projects",
      aboutKicker: "ABOUT",
      aboutTitle: "I build websites for companies,\nwith AI as co-pilot.",
      stackKicker: "STACK",
      stackTitle: "Tools of the trade",
      skillsKicker: "SKILLS",
      skillsTitle: "How I work",
      projectsKicker: "WORK",
      projectsTitle: "Recent projects",
      contactKicker: "CONTACT",
      contactTitle: "Let's talk about your project",
      contactLead: "Got an idea, a site to redo, a business that wants to be found online? Write me.",
      viewLive: "View live",
      caseStudy: "Case study",
      scrollHint: "Scroll",
      footerNote: "Designed & coded with AI as co-pilot",
      labelYear: "Year",
      labelStack: "Stack",
      labelFeatures: "Features",
      navWork: "Work",
      navAbout: "About",
      navStack: "Stack",
      navContact: "Contact",
      // Case study
      caseBackTo: "Back to portfolio",
      caseRole: "Role",
      caseTeam: "Team",
      caseYear: "Year",
      caseChallenge: "The challenge",
      caseApproach: "The approach",
      caseOutcome: "Outcome",
      caseStackTitle: "Tech stack",
      caseFeaturesTitle: "Key features",
      caseCtaText: "Want a site like this for your business?",
      caseCtaBtn: "Let's start",
      caseComingSoon: "Live soon",
      // Contact form
      formName: "Name",
      formEmail: "Email",
      formCompany: "Company (optional)",
      formBudget: "Rough budget",
      formMessage: "Tell me about your project",
      formSend: "Send message",
      formSending: "Sending…",
      formSuccess: "Message sent. I'll reply within 24h.",
      formError: "Something went wrong. Try again or email me directly.",
      formRequired: "Required field",
      formInvalidEmail: "Invalid email",
      formBudgetOpts: ["< €2k", "€2–5k", "€5–10k", "€10k+", "TBD"],
    },
  },
};

export default data;
